### ISSUE TITLE
Can't find yarn.lock

### ISSUE THREAD

**Issue by SleeplessByte** [Simek/yarn-lock-changes#17]
Hi there!

I followed the instructions and running into the following error message:

![image](https://user-images.githubusercontent.com/1964376/116548558-b2c9fa80-a8f4-11eb-838d-300e2471ea7b.png)

I've made sure `yarn.lock` is available, at the root of the repository. It doesn't matter if the file is changes or not in the PR. Here is an example of the file changes in the PR:

![image](https://user-images.githubusercontent.com/1964376/116548586-bd848f80-a8f4-11eb-9f76-9488a70e94dc.png)

Any guidance how to debug or resolve?

**Comment by Simek** [comment]
Hi @SleeplessByte, thank you for testing the action! 🙂 

I have a few questions:
* is you repository public or private?
* are you sure that the action runs only on PR? (`on: [pull_request]`)

The issue also might be thrown if you are not checking out the branch in workflow, see:
* https://github.com/Simek/yarn-lock-changes/blob/main/.github/workflows/main.yml

Please let me know if you will be able to resolve the issue with this feedback. If yes, I will update the Readme to include better workflow example, if no, we can investigate this further.

**Comment by SleeplessByte** [comment]
- it's private
- yes :)

Forcing a check-out was the key!
