### ISSUE TITLE
Feature request: npm package-lock.json support / version

### ISSUE THREAD

**Issue by adam-lynch** [Simek/yarn-lock-changes#25]
Nice project. Support for / an equivalent for npm's package-lock.json would be great. I'm not sure how possible that is

**Comment by Simek** [comment]
Hi @adam-lynch, thank you for the kind words! 🙂 

Adding this feature or creating an equivalent of this action for NPM lock should be possible, for example, there is a lock parser from Snyk which supports files created by both managers - https://www.npmjs.com/package/snyk-nodejs-lockfile-parser

However, I'm not sure if this should be added to `yarn-lock-changes` as a feature or this should become a separate action. I think it would be a bit confusing or counterintuitive for the potential NPM users, who will need to install "`yarn` tool". Also at this moment in time I would rather not change the action name, so it's not an easy choice. 

I will have that feature request in mind and I will experiment a bit with different solutions.

**Comment by Simek** [comment]
It looks like someone already have forked the action and stated the refactor to support `package-lock.json`: 
* https://github.com/Mheaus/package-lock-changes

**Comment by adam-lynch** [comment]
Thanks. I agree with everything you said. I'll keep an eye on that project you linked :)

**Comment by codepunkt** [comment]
@Simek @adam-lynch  The linked fork didn't work for me using NPM v2 lockfiles - so I made my own one, which works fine:

https://github.com/codepunkt/npm-lockfile-changes

Enjoy!

**Comment by Simek** [comment]
That nice to see, good job @codepunkt!

I think the issue can be closed now.

---

Btw. We can cross-link the actions in the notice in Readme files, what do you think? I have something like that in mind:

> If you are looking for PACKAGE_MANAGER_NAME action check out `PACKAGE_NAME` (linked to other action GH Marketplace)

**Comment by kfiven** [comment]
Hi @Simek , @codepunkt 's fork isn't working reliably for me. It only shows updates (no addition, remove). So there isn't any good alternative to this action for package-lock, hope you'll reconsider adding that in this action.
