### ISSUE TITLE
Feature Request: Support `yarn.lock` generated by Yarn 2 and later

### ISSUE THREAD

**Issue by tido64** [Simek/yarn-lock-changes#34]
The format of `yarn.lock` changed in a more recent version of Yarn:

```
Error: Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in lockfile
```

It would be great the new format is also supported. Especially because Yarn 3 is pretty promising.

You can find the full build log here: https://github.com/microsoft/react-native-test-app/runs/3182759815?check_suite_focus=true

**Comment by Simek** [comment]
Hi @tido, thank you feature request! 👍 

Unfortunately it looks like the official Yarn lock parser (which this action uses) is no longer maintained and will not be updated to support v2 or v3 locks:
* https://github.com/yarnpkg/yarn/tree/master/packages/lockfile

I will explore the other possibilities where it comes to the lock parser, one of which might be interesting is a package from Snyk, which currently support Yarn v1 and v2 locks (as well as npm lock, which support was discussed earlier in #25):
* https://github.com/snyk/nodejs-lockfile-parser
