### ISSUE TITLE
error with v0.11.0 for yarn 3 lock file

### ISSUE THREAD

**Issue by ValentinH** [Simek/yarn-lock-changes#55]
Following the latest addition for Yarn 3 support, I just tried it on my repository.
However, I still get an error, see this log:
![image](https://user-images.githubusercontent.com/2678610/178233106-dbd3493c-1b99-4bc5-8c90-d9a337089d12.png)

**Comment by ValentinH** [comment]
If it can help, here's the 2 first block of our yarn.lock:
```
# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 5
  cacheKey: 8

"@ampproject/remapping@npm:^2.1.0":
  version: 2.1.2
  resolution: "@ampproject/remapping@npm:2.1.2"
  dependencies:
    "@jridgewell/trace-mapping": ^0.3.0
  checksum: e023f92cdd9723f3042cde3b4d922adfeef0e198aa73486b0b6c034ad36af5f96e5c0cc72b335b30b2eb9852d907efc92af6bfcd3f4b4d286177ee32a189cf92
  languageName: node
  linkType: hard

"@apollo/client@npm:3.5.6":
  version: 3.5.6
  resolution: "@apollo/client@npm:3.5.6"
  dependencies:
    "@graphql-typed-document-node/core": ^3.0.0
    "@wry/context": ^0.6.0
    "@wry/equality": ^0.5.0
    "@wry/trie": ^0.3.0
    graphql-tag: ^2.12.3
    hoist-non-react-statics: ^3.3.2
    optimism: ^0.16.1
    prop-types: ^15.7.2
    symbol-observable: ^4.0.0
    ts-invariant: ^0.9.4
    tslib: ^2.3.0
    zen-observable-ts: ^1.2.0
  peerDependencies:
    graphql: ^14.0.0 || ^15.0.0 || ^16.0.0
    react: ^16.8.0 || ^17.0.0
    subscriptions-transport-ws: ^0.9.0 || ^0.11.0
  peerDependenciesMeta:
    react:
      optional: true
    subscriptions-transport-ws:
      optional: true
  checksum: 503cc1f34114be1c0fe411744881078f781c6d33b431199dce3813e7cbf85f4cf2f06fd283b08c00f92c0ccea83ef531aa3c5d2215ba2937fb1cc208fbe83300
  languageName: node
  linkType: hard
```

**Comment by Simek** [comment]
Hello @ValentinH, thank you for the bug report! 🙏 

I have an idea what might be wrong, but it would be nice if you can provide link to the repository (if it's public) or whole `yarn.lock` file, so I will be able to confirm my suspicions.

**Comment by ValentinH** [comment]
Thank you for the quick answer and this cool project!
 I've sent you an email with our `yarn.lock` file 🙂

**Comment by Simek** [comment]
New version including the fix has been published as:
* https://github.com/Simek/yarn-lock-changes/releases/tag/v0.11.1

If you use `main` as version, the new version will be used in the next action runs, if not, you will need to bump the version to the latest release.

**Comment by ValentinH** [comment]
Thank you for the quick fix, it works perfectly now! 🎉
